### ISSUE TITLE
subscribe button height consistency

### ISSUE THREAD

**Issue by Confidenceman02** [ReactivePixels/reactive-pixels-app#69]
<img width="496" alt="screen shot 2018-03-25 at 6 06 17 pm" src="https://user-images.githubusercontent.com/25443812/37872622-42d8f366-3057-11e8-8aaa-7cce08fe4800.png">

**Comment by rodleviton** [comment]
<img width="2032" alt="screen shot 2018-03-26 at 8 22 42 pm" src="https://user-images.githubusercontent.com/1480083/37898037-7ada35e0-3133-11e8-855e-25f14aa6efce.png">
