### ISSUE TITLE
author pill too wide

### ISSUE THREAD

**Issue by Confidenceman02** [ReactivePixels/reactive-pixels-app#72]
![screen shot 2018-03-26 at 11 27 47 am](https://user-images.githubusercontent.com/25443812/37881816-c310e322-30e8-11e8-8567-8ce674f1115e.png)

**Comment by rodleviton** [comment]
This should be a `chip` component as this is used in other areas of the app.

<img width="155" alt="screen shot 2018-03-26 at 8 50 46 pm" src="https://user-images.githubusercontent.com/1480083/37899504-67daf6a6-3137-11e8-85bf-9d43b2ed9664.png">
<img width="457" alt="screen shot 2018-03-26 at 8 50 55 pm" src="https://user-images.githubusercontent.com/1480083/37899505-68109da6-3137-11e8-80fe-6f151af3dba6.png">
