### ISSUE TITLE
Logging in with invite token

### ISSUE THREAD

**Issue by Confidenceman02** [ReactivePixels/reactive-pixels-app#78]
### Current behaviour
After entering token and clicking enter modal says "Signing you in". After signed in "Sign in with Github" button does not reflect signed in users avatar.

### Expected
After signing in users avatar should show instead of the "Sign in with Github" button.
![screen shot 2018-03-27 at 12 46 38 pm](https://user-images.githubusercontent.com/25443812/37942519-2ed2dfbc-31bf-11e8-9643-c1dd505345aa.png)

**Comment by rodleviton** [comment]
FirebaseAuth stores credentials in browser indexeddb, but this does not contain the Github access token which we use to authenticate all API calls to github resources. This is why the user is technically signed in but we cannot retrieve there github profile as we do not have an access token. I have added condition to not automatically sign user in using stored indexeddb credentials if we do not have accessToken.
