### ISSUE TITLE
Signing you in modal

### ISSUE THREAD

**Issue by Confidenceman02** [ReactivePixels/reactive-pixels-app#79]
### Current
When refreshing page after entering invite token "Signing you in" modal displays. When navigating to any page  by entering url, "Signing you in" modal appears.
### Expected
After signing in with token and the initial "Signing you in" modal appearing it should keep popping up until the user is not signed in.

**Comment by rodleviton** [comment]
This is expected browser behaviour. Issue only happens when browser is refreshed. React Router is re-initialised.
